on: [push]

jobs:
  test_golang_job:
    runs-on: ubuntu-latest
    name: Test golang source
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: ./.github/actions/golang
